quadruped:
    # Publish all joint states
    joint_state_controller:
        type: joint_state_contoller/JointStateController
        publish_rate: 50

    # Position Controllers
    # Set up all joints as follows
    # Ensure that the hardware interface in quadruped.trans is the same as
    # the hardware interface mentioned here, else there will be an error
    Hip1_position_controller:
        type: position_controllers/JointPositionController
        joint: Rev14
        pid: {p: 100.0, i: 0.01, d: 10.0}
