controller_list:
  - name: fake_front_right_leg_controller
    joints:
      - front_right_leg3_joint
      - front_right_leg2_joint
      - front_right_leg1_joint
  - name: fake_front_left_leg_controller
    joints:
      - front_left_leg3_joint
      - front_left_leg2_joint
      - front_left_leg1_joint
  - name: fake_back_right_leg_controller
    joints:
      - back_right_leg3_joint
      - back_right_leg2_joint
      - back_right_leg1_joint
  - name: fake_back_left_leg_controller
    joints:
      - back_left_leg3_joint
      - back_left_leg2_joint
      - back_left_leg1_joint
  - name: fake_base_controller
    joints:
      []
initial:  # Define initial robot poses.
#  - group: front_right_leg
#    pose: home
