import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

f = 'fundamental_freq_analysis.csv'
df = pd.read_csv(f)
def plot_freq_vs_tst():
    lst = [20, 50, 100, 150]
    colors = ['b', 'g', 'r', 'c']
    fig, ax = plt.subplots(4, 2, figsize = (10, 20))
    for i in range(len(lst)):
        val = df[df['Tsw']==lst[i]]
        ax[0][0].plot(val['Tst'], val['Fundamental Frequency Hip 1'], colors[i], label = 'Tsw {f}'.format(f = lst[i]))
        ax[0][0].set_xlabel('Tst')
        ax[0][0].set_ylabel('Fundamental Frequency Hip 1')
        ax[0][0].legend()
        ax[0][1].plot(val['Tst'], val['Fundamental Frequency Knee 1'], colors[i], label = 'Tsw {f}'.format(f = lst[i]))
        ax[0][1].set_xlabel('Tst')
        ax[0][1].set_ylabel('Fundamental Frequency Knee 1')
        ax[0][1].legend()
        ax[1][0].plot(val['Tst'], val['Fundamental Frequency Hip 2'], colors[i], label = 'Tsw {f}'.format(f = lst[i]))
        ax[1][0].set_xlabel('Tst')
        ax[1][0].set_ylabel('Fundamental Frequency Hip 2')
        ax[1][0].legend()
        ax[1][1].plot(val['Tst'], val['Fundamental Frequency Knee 2'], colors[i], label = 'Tsw {f}'.format(f = lst[i]))
        ax[1][1].set_xlabel('Tst')
        ax[1][1].set_ylabel('Fundamental Frequency Knee 2')
        ax[1][1].legend()
        ax[2][0].plot(val['Tst'], val['Fundamental Frequency Hip 3'], colors[i], label = 'Tsw {f}'.format(f = lst[i]))
        ax[2][0].set_xlabel('Tst')
        ax[2][0].set_ylabel('Fundamental Frequency Hip 3')
        ax[2][0].legend()
        ax[2][1].plot(val['Tst'], val['Fundamental Frequency Knee 3'], colors[i], label = 'Tsw {f}'.format(f = lst[i]))
        ax[2][1].set_xlabel('Tst')
        ax[2][1].set_ylabel('Fundamental Frequency Knee 3')
        ax[2][1].legend()
        ax[3][0].plot(val['Tst'], val['Fundamental Frequency Hip 4'], colors[i], label = 'Tsw {f}'.format(f = lst[i]))
        ax[3][0].set_xlabel('Tst')
        ax[3][0].set_ylabel('Fundamental Frequency Hip 4')
        ax[3][0].legend()
        ax[3][1].plot(val['Tst'], val['Fundamental Frequency Knee 4'], colors[i], label = 'Tsw {f}'.format(f = lst[i]))
        ax[3][1].set_xlabel('Tst')
        ax[3][1].set_ylabel('Fundamental Frequency Knee 4')
        ax[3][1].legend()
    plt.show()
    fig.savefig('../images/TstVsFundamentalFreq.png')

def plot_freq_vs_tsw():
    lst = [70, 150, 300, 450]
    colors =  ['b', 'g', 'r', 'c']
    fig, ax = plt.subplots(4, 2, figsize = (10, 20))
    for i in range(len(lst)):
        val = df[df['Tst']==lst[i]]
        ax[0][0].plot(val['Tsw'], val['Fundamental Frequency Hip 1'], colors[i], label = 'Tst {f}'.format(f = lst[i]))
        ax[0][0].set_xlabel('Tsw')
        ax[0][0].set_ylabel('Fundamental Frequency Hip 1')
        ax[0][0].legend()
        ax[0][1].plot(val['Tsw'], val['Fundamental Frequency Knee 1'], colors[i], label = 'Tst {f}'.format(f = lst[i]))
        ax[0][1].set_xlabel('Tsw')
        ax[0][1].set_ylabel('Fundamental Frequency Knee 1')
        ax[0][1].legend()
        ax[1][0].plot(val['Tsw'], val['Fundamental Frequency Hip 2'], colors[i], label = 'Tst {f}'.format(f = lst[i]))
        ax[1][0].set_xlabel('Tsw')
        ax[1][0].set_ylabel('Fundamental Frequency Hip 2')
        ax[1][0].legend()
        ax[1][1].plot(val['Tsw'], val['Fundamental Frequency Knee 2'], colors[i], label = 'Tst {f}'.format(f = lst[i]))
        ax[1][1].set_xlabel('Tsw')
        ax[1][1].set_ylabel('Fundamental Frequency Knee 2')
        ax[1][1].legend()
        ax[2][0].plot(val['Tsw'], val['Fundamental Frequency Hip 3'], colors[i], label = 'Tst {f}'.format(f = lst[i]))
        ax[2][0].set_xlabel('Tsw')
        ax[2][0].set_ylabel('Fundamental Frequency Hip 3')
        ax[2][0].legend()
        ax[2][1].plot(val['Tsw'], val['Fundamental Frequency Knee 3'], colors[i], label = 'Tst {f}'.format(f = lst[i]))
        ax[2][1].set_xlabel('Tsw')
        ax[2][1].set_ylabel('Fundamental Frequency Knee 3')
        ax[2][1].legend()
        ax[3][0].plot(val['Tsw'], val['Fundamental Frequency Hip 4'], colors[i], label = 'Tst {f}'.format(f = lst[i]))
        ax[3][0].set_xlabel('Tsw')
        ax[3][0].set_ylabel('Fundamental Frequency Hip 4')
        ax[3][0].legend()
        ax[3][1].plot(val['Tsw'], val['Fundamental Frequency Knee 4'], colors[i], label = 'Tst {f}'.format(f = lst[i]))
        ax[3][1].set_xlabel('Tsw')
        ax[3][1].set_ylabel('Fundamental Frequency Knee 4')
        ax[3][1].legend()
    plt.show()
    fig.savefig('../images/TswVsFundamentalFreq.png')

def plot_speed_vs_freq(test_type = None):
    fig, ax = plt.subplots(4, 2, figsize = (10, 20))
    ax[0][0].plot(df['speed'], df['Fundamental Frequency Hip 1'])
    ax[0][0].set_xlabel('speed')
    ax[0][0].set_ylabel('Fundamental Frequency Hip 1')
    ax[0][1].plot(df['speed'], df['Fundamental Frequency Knee 1'])
    ax[0][1].set_xlabel('speed')
    ax[0][1].set_ylabel('Fundamental Frequency Knee 1')
    ax[1][0].plot(df['speed'], df['Fundamental Frequency Hip 2'])
    ax[1][0].set_xlabel('speed')
    ax[1][0].set_ylabel('Fundamental Frequency Hip 2')
    ax[1][1].plot(df['speed'], df['Fundamental Frequency Knee 2'])
    ax[1][1].set_xlabel('speed')
    ax[1][1].set_ylabel('Fundamental Frequency Knee 2')
    ax[2][0].plot(df['speed'], df['Fundamental Frequency Hip 3'])
    ax[2][0].set_xlabel('speed')
    ax[2][0].set_ylabel('Fundamental Frequency Hip 3')
    ax[2][1].plot(df['speed'], df['Fundamental Frequency Knee 3'])
    ax[2][1].set_xlabel('speed')
    ax[2][1].set_ylabel('Fundamental Frequency Knee 3')
    ax[3][0].plot(df['speed'], df['Fundamental Frequency Hip 4'])
    ax[3][0].set_xlabel('speed')
    ax[3][0].set_ylabel('Fundamental Frequency Hip 4')
    ax[3][1].plot(df['speed'], df['Fundamental Frequency Knee 4'])
    ax[3][1].set_xlabel('speed')
    ax[3][1].set_ylabel('Fundamental Frequency Knee 4')
    plt.show()
    if test_type is not None:
        fig.savefig('../images/speedVsFundamentalFreq_{t}.png'.format(t=test_type))
    else:
        fig.savefig('../images/speedVsFundamentalFreq.png')

#plot_freq_vs_tst()
#plot_freq_vs_tsw()
#plot_speed_vs_freq()
f = 'fundamental_freq_vs_theta_analysis.csv'
df = pd.read_csv(f)

def plot_theta_vs_freq():
    fig, ax = plt.subplots(4, 2, figsize = (10, 20))
    ax[0][0].plot(df['theta'], df['Fundamental Frequency Hip 1'])
    ax[0][0].set_xlabel('theta')
    ax[0][0].set_ylabel('Fundamental Frequency Hip 1')
    ax[0][1].plot(df['theta'], df['Fundamental Frequency Knee 1'])
    ax[0][1].set_xlabel('theta')
    ax[0][1].set_ylabel('Fundamental Frequency Knee 1')
    ax[1][0].plot(df['theta'], df['Fundamental Frequency Hip 2'])
    ax[1][0].set_xlabel('theta')
    ax[1][0].set_ylabel('Fundamental Frequency Hip 2')
    ax[1][1].plot(df['theta'], df['Fundamental Frequency Knee 2'])
    ax[1][1].set_xlabel('theta')
    ax[1][1].set_ylabel('Fundamental Frequency Knee 2')
    ax[2][0].plot(df['theta'], df['Fundamental Frequency Hip 3'])
    ax[2][0].set_xlabel('theta')
    ax[2][0].set_ylabel('Fundamental Frequency Hip 3')
    ax[2][1].plot(df['theta'], df['Fundamental Frequency Knee 3'])
    ax[2][1].set_xlabel('theta')
    ax[2][1].set_ylabel('Fundamental Frequency Knee 3')
    ax[3][0].plot(df['theta'], df['Fundamental Frequency Hip 4'])
    ax[3][0].set_xlabel('theta')
    ax[3][0].set_ylabel('Fundamental Frequency Hip 4')
    ax[3][1].plot(df['theta'], df['Fundamental Frequency Knee 4'])
    ax[3][1].set_xlabel('theta')
    ax[3][1].set_ylabel('Fundamental Frequency Knee 4')
    plt.show()
    fig.savefig('../images/thetaVsFundamentalFreq.png')

#plot_speed_vs_freq('varying_theta')
#plot_theta_vs_freq()

f = 'fundamental_freq_vs_Tst_analysis.csv'
df = pd.read_csv(f)

def plot_Tst_vs_freq_const_Tsw():
    fig, ax = plt.subplots(4, 2, figsize = (10, 20))
    ax[0][0].plot(df['Tst'], df['Fundamental Frequency Hip 1'])
    ax[0][0].set_xlabel('Tst')
    ax[0][0].set_ylabel('Fundamental Frequency Hip 1')
    ax[0][1].plot(df['Tst'], df['Fundamental Frequency Knee 1'])
    ax[0][1].set_xlabel('Tst')
    ax[0][1].set_ylabel('Fundamental Frequency Knee 1')
    ax[1][0].plot(df['Tst'], df['Fundamental Frequency Hip 2'])
    ax[1][0].set_xlabel('Tst')
    ax[1][0].set_ylabel('Fundamental Frequency Hip 2')
    ax[1][1].plot(df['Tst'], df['Fundamental Frequency Knee 2'])
    ax[1][1].set_xlabel('Tst')
    ax[1][1].set_ylabel('Fundamental Frequency Knee 2')
    ax[2][0].plot(df['Tst'], df['Fundamental Frequency Hip 3'])
    ax[2][0].set_xlabel('Tst')
    ax[2][0].set_ylabel('Fundamental Frequency Hip 3')
    ax[2][1].plot(df['Tst'], df['Fundamental Frequency Knee 3'])
    ax[2][1].set_xlabel('Tst')
    ax[2][1].set_ylabel('Fundamental Frequency Knee 3')
    ax[3][0].plot(df['Tst'], df['Fundamental Frequency Hip 4'])
    ax[3][0].set_xlabel('Tst')
    ax[3][0].set_ylabel('Fundamental Frequency Hip 4')
    ax[3][1].plot(df['Tst'], df['Fundamental Frequency Knee 4'])
    ax[3][1].set_xlabel('Tst')
    ax[3][1].set_ylabel('Fundamental Frequency Knee 4')
    plt.show()
    fig.savefig('../images/TstVsFundamentalFreqConstTsw.png')

plot_speed_vs_freq('varying_Tst_const_Tsw')
plot_Tst_vs_freq_const_Tsw()

f = 'fundamental_freq_vs_Tsw_analysis.csv'
df = pd.read_csv(f)

def plot_Tsw_vs_freq_const_Tst():
    fig, ax = plt.subplots(4, 2, figsize = (10, 20))
    ax[0][0].plot(df['Tsw'], df['Fundamental Frequency Hip 1'])
    ax[0][0].set_xlabel('Tsw')
    ax[0][0].set_ylabel('Fundamental Frequency Hip 1')
    ax[0][1].plot(df['Tsw'], df['Fundamental Frequency Knee 1'])
    ax[0][1].set_xlabel('Tsw')
    ax[0][1].set_ylabel('Fundamental Frequency Knee 1')
    ax[1][0].plot(df['Tsw'], df['Fundamental Frequency Hip 2'])
    ax[1][0].set_xlabel('Tsw')
    ax[1][0].set_ylabel('Fundamental Frequency Hip 2')
    ax[1][1].plot(df['Tsw'], df['Fundamental Frequency Knee 2'])
    ax[1][1].set_xlabel('Tsw')
    ax[1][1].set_ylabel('Fundamental Frequency Knee 2')
    ax[2][0].plot(df['Tsw'], df['Fundamental Frequency Hip 3'])
    ax[2][0].set_xlabel('Tsw')
    ax[2][0].set_ylabel('Fundamental Frequency Hip 3')
    ax[2][1].plot(df['Tsw'], df['Fundamental Frequency Knee 3'])
    ax[2][1].set_xlabel('Tsw')
    ax[2][1].set_ylabel('Fundamental Frequency Knee 3')
    ax[3][0].plot(df['Tsw'], df['Fundamental Frequency Hip 4'])
    ax[3][0].set_xlabel('Tsw')
    ax[3][0].set_ylabel('Fundamental Frequency Hip 4')
    ax[3][1].plot(df['Tsw'], df['Fundamental Frequency Knee 4'])
    ax[3][1].set_xlabel('Tsw')
    ax[3][1].set_ylabel('Fundamental Frequency Knee 4')
    plt.show()
    fig.savefig('../images/TswVsFundamentalFreqConstTst.png')

plot_speed_vs_freq('varying_Tsw_const_Tst')
plot_Tsw_vs_freq_const_Tst()

