quadruped:
  moveit_sim_hw_interface:
    joint_model_group: todo_group_name
    joint_model_group_pose: todo_state_name
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - back_left_leg3_joint
      - back_left_leg2_joint
      - back_left_leg1_joint
      - back_right_leg3_joint
      - back_right_leg2_joint
      - back_right_leg1_joint
      - front_left_leg3_joint
      - front_left_leg2_joint
      - front_left_leg1_joint
      - front_right_leg3_joint
      - front_right_leg2_joint
      - front_right_leg1_joint
    sim_control_mode: 1  # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  front_right_leg_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - front_right_leg1_joint
      - front_right_leg2_joint
      - front_right_leg3_joint
    gains:
      - front_right_leg1_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      - front_right_leg2_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      - front_right_leg3_joint: {p: 200, d: 1, i: 30, i_clamp: 100}

  front_left_leg_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - front_left_leg1_joint
      - front_left_leg2_joint
      - front_left_leg3_joint
    gains:
      - front_left_leg1_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      - front_left_leg2_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      - front_left_leg3_joint: {p: 200, d: 1, i: 30, i_clamp: 100}

  back_right_leg_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - back_right_leg1_joint
      - back_right_leg2_joint
      - back_right_leg3_joint
    gains:
      - back_right_leg1_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      - back_right_leg2_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      - back_right_leg3_joint: {p: 200, d: 1, i: 30, i_clamp: 100}

  back_left_leg_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - back_left_leg1_joint
      - back_left_leg2_joint
      - back_left_leg3_joint
    gains:
      - back_left_leg1_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      - back_left_leg2_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      - back_left_leg3_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
